[servers]
    [servers.redis]
    host = "localhost"
    port = 6379
    db = 0

    [servers.inlfux]
    host = "0.0.0.0"
    port = 51001

    [servers.postgre]
    host = "192.168.110.11"
    port = 15432
    dbname = 'thermal_imaging'
    users = 'gaonpf'


[arima]
window_size = 5
step_size = 5